# Generated by Django 4.2.7 on 2023-11-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_first_name_remove_profile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_child',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='is_parent',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('parent', 'Parent'), ('child', 'Child')], default='child', max_length=10),
        ),
    ]
