# Generated by Django 4.2.7 on 2023-11-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_is_child_remove_profile_is_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='unique_id',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
